### ISSUE TITLE
Buen trabajoo. Anda en rpi3

### ISSUE THREAD

**Issue by Askmewho** [wfx/teg#4]
Lo testee en la pi y anda bien  me gustaria poder usar el tablero original. Lo deberías ofrecer de forma soterrada. Ha pasado mucho tiempo. Quiza alguien lo haga. Le daria un toque de nostalgia muy pro. Otra cosa buena seria poder poner custom rules. En mi casa se jugaba con las reglas de casa. Una pequeña animacion de dados tmb. Un gestor de pactos. Fua. Un laburo para todo un equipo

**Comment by wfx** [comment]
Sorry, what?

Sat Mar 09 17:37:22 GMT+01:00 2019 Askmewho <notifications@github.com>:

**Comment by Askmewho** [comment]
sorry, I spoken in spanish because i believed than you where an spanish speaker. i've tested this on rpi3 and it works as expected

* just to congrats you achievement
* hope you can improve thinks like:
                * real tTEG map with some minor changes to avoid copyright problems
                 * pact management system
                 * custom rules
                 * some animations (like on dices), war soundtracks?

**Comment by edomato** [comment]
Sorry I didn't reply before and yes, I do speak Spanish but in general, most projects involves people from all around the world so English use to be the common language.

Of your proposals, the most complicate one is the "custom rules" one since doing something very generic is not really easy. So, we should agreed on the term "custom" :smile: 

Which custom rule would you like to see?

The animated dices is not really complicated, the sounds if another issue since either we find creative commons music and sounds, or we find a composer that can create those assets.

Well, that's all for now.
Greets

**Comment by Askmewho** [comment]
In my home we have several custom rooms about how to gather armys. It doesnt have sense than I introduce them. But lets do that...the main rule its than after 6 round you can only gather army per countries (1\2) on alternated sequence . seven round no;eight, yes; nine,no; etc. 2do rule changing cards only give you 5 armys, always. The all idea its to get shorter games and less amount of armys across the game. That kind of custom rules. Thanks to this game. Hillarius name. Can I make a custom map ? Just to use the same than the real teg. Which tool you used to make the others???

**Comment by wfx** [comment]
If I remember the real map use some allowed content from the Austrian army.

You can use any graphics software. I used mostly gimp, blender and inkscape.

We have always plans to rewrite teg ( like html/js node attempt) and use different rules have to be one of its features.

wfx

Mon Mar 11 17:02:56 GMT+01:00 2019 Askmewho <notifications@github.com>:
